spring:
    datasource:
        url: 'jdbc:postgresql://localhost:5432/postgres'
        username: postgres
        password: password

jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

clients:
    open-library:
        base-url: 'https://openlibrary.org'
